### ISSUE TITLE
Hover effect broken

### ISSUE THREAD

**Issue by SimpleCookie** [web-tiki/responsive-grid-of-hexagons#22]
This issue may not occur to all of you. It happens to me because of my particular case, I modified the breakpoints a bit to suit my case better. But now the problem is; the hover effect does not work in the mobile version (and other device sizes).

You can find the issue on [devgroup.se](devgroup.se)
I'm not sure if it is something you want to work on? I plan to look into it myself when I have time, I will post a solution when I do, if I do for you guys.

**Comment by web-tiki** [comment]
The issue is not related to the grid of hexagons. 
There is an element over the hexagons (second div in your nav) that prevents the hover effect (and any other interactions) on the grid. 
See the following image: 

![issue](https://user-images.githubusercontent.com/8065876/29060729-4e5bea2c-7c1b-11e7-8993-9a892a7cecf6.png)

**Comment by SimpleCookie** [comment]
Yes you are correct! Thank you and my apologies for blaming this wonderful grid system! <3
